global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'digital_twin'
    static_configs:
      - targets: ['digital_twin:8000'] 